name: flutter_number_captcha
description: Flutter plugin to display random number captcha. This plugin will show dialog and validate number captcha.
version: 0.0.8
homepage: https://github.com/lustea00/flutter_number_captcha

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

